///|
#deprecated
pub extend ActuatorLike with Eq::{not_equal, equal}

///|
#deprecated
pub extend Body with Eq::{not_equal, equal}

///|
#deprecated
pub extend BodyLike with Eq::{not_equal, equal}

///|
#deprecated
pub extend CoulombKineticFriction with Eq::{not_equal, equal}

///|
#deprecated
pub extend CylindricalJoint with Eq::{not_equal, equal}

///|
#deprecated
pub extend DuffingSpring with Eq::{not_equal, equal}

///|
#deprecated
pub extend Force with Eq::{not_equal, equal}

///|
#deprecated
pub extend ForceActuator with Eq::{not_equal, equal}

///|
#deprecated
pub extend Inertia with Eq::{not_equal, equal}

///|
#deprecated
pub extend JointAttachment with Eq::{not_equal, equal}

///|
#deprecated
pub extend JointInterframe with Eq::{not_equal, equal}

///|
#deprecated
pub extend JointLike with Eq::{not_equal, equal}

///|
#deprecated
pub extend JointsMethod with Eq::{not_equal, equal}

///|
#deprecated
pub extend KanesMethod with Eq::{not_equal, equal}

///|
#deprecated
pub extend LagrangesMethod with Eq::{not_equal, equal}

///|
#deprecated
pub extend LinearDamper with Eq::{not_equal, equal}

///|
#deprecated
pub extend LinearPathway with Eq::{not_equal, equal}

///|
#deprecated
pub extend LinearSpring with Eq::{not_equal, equal}

///|
#deprecated
pub extend Linearizer with Eq::{not_equal, equal}

///|
#deprecated
pub extend Load with Eq::{not_equal, equal}

///|
#deprecated
pub extend MechanicsBackend with Eq::{not_equal, equal}

///|
#deprecated
pub extend ObstacleSetPathway with Eq::{not_equal, equal}

///|
#deprecated
pub extend Particle with Eq::{not_equal, equal}

///|
#deprecated
pub extend PathwayLike with Eq::{not_equal, equal}

///|
#deprecated
pub extend PinJoint with Eq::{not_equal, equal}

///|
#deprecated
pub extend PlanarJoint with Eq::{not_equal, equal}

///|
#deprecated
pub extend PrismaticJoint with Eq::{not_equal, equal}

///|
#deprecated
pub extend RigidBody with Eq::{not_equal, equal}

///|
#deprecated
pub extend SphericalJoint with Eq::{not_equal, equal}

///|
#deprecated
pub extend SymbolicSystem with Eq::{not_equal, equal}

///|
#deprecated
pub extend System with Eq::{not_equal, equal}

///|
#deprecated
pub extend Torque with Eq::{not_equal, equal}

///|
#deprecated
pub extend TorqueActuator with Eq::{not_equal, equal}

///|
#deprecated
pub extend WeldJoint with Eq::{not_equal, equal}

///|
#deprecated
pub extend WrappingCone with Eq::{not_equal, equal}

///|
#deprecated
pub extend WrappingCylinder with Eq::{not_equal, equal}

///|
#deprecated
pub extend WrappingGeometryLike with Eq::{not_equal, equal}

///|
#deprecated
pub extend WrappingPathway with Eq::{not_equal, equal}

///|
#deprecated
pub extend WrappingSphere with Eq::{not_equal, equal}
