///|
#deprecated
pub extend BosonOpExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend BosonOpExpr with Show::{to_string, output}

///|
#deprecated
pub extend CG with Eq::{not_equal, equal}

///|
#deprecated
pub extend CModExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend DensityExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend DensityTerm with Eq::{not_equal, equal}

///|
#deprecated
pub extend DifferentialOperatorExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend FermionOpExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend FermionOpExpr with Show::{to_string, output}

///|
#deprecated
pub extend FourierExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend GateExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend GateExpr with Show::{to_string, output}

///|
#deprecated
pub extend GateIdentity with Show::{to_string, output}

///|
#deprecated
pub extend GateKind with Eq::{not_equal, equal}

///|
#deprecated
pub extend GateRule with Eq::{not_equal, equal}

///|
#deprecated
pub extend GateRule with Show::{to_string, output}

///|
#deprecated
pub extend HilbertSpace with Add::{add}

///|
#deprecated
pub extend HilbertSpace with Eq::{not_equal, equal}

///|
#deprecated
pub extend HilbertSpace with Mul::{mul}

///|
#deprecated
pub extend HilbertSpace with Show::{to_string, output}

///|
#deprecated
pub extend JzState with Eq::{not_equal, equal}

///|
#deprecated
pub extend JzState with Show::{to_string, output}

///|
#deprecated
pub extend MatrixScalarValue with Eq::{not_equal, equal}

///|
#deprecated
pub extend MatrixScalarValue with Show::{to_string, output}

///|
#deprecated
pub extend OperatorExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend OperatorExpr with Show::{to_string, output}

///|
#deprecated
pub extend OperatorFlavor with Eq::{not_equal, equal}

///|
#deprecated
pub extend OracleGateExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend PauliExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend PauliExpr with Show::{to_string, output}

///|
#deprecated
pub extend PauliKind with Eq::{not_equal, equal}

///|
#deprecated
pub extend QExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend QExpr with Show::{to_string, output}

///|
#deprecated
pub extend Qasm with Eq::{not_equal, equal}

///|
#deprecated
pub extend QasmDefinition with Eq::{not_equal, equal}

///|
#deprecated
pub extend QuantumKind with Eq::{not_equal, equal}

///|
#deprecated
pub extend QuantumKind with Show::{to_string, output}

///|
#deprecated
pub extend QubitExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend QubitExpr with Show::{to_string, output}

///|
#deprecated
pub extend RkExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend RotationExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend RotationExpr with Show::{to_string, output}

///|
#deprecated
pub extend SigmaZState with Eq::{not_equal, equal}

///|
#deprecated
pub extend SigmaZState with Show::{to_string, output}

///|
#deprecated
pub extend SpinCoupleOrder with Eq::{not_equal, equal}

///|
#deprecated
pub extend SpinCoupling with Eq::{not_equal, equal}

///|
#deprecated
pub extend SpinResolvedCoupling with Eq::{not_equal, equal}

///|
#deprecated
pub extend SpinResolvedPair with Eq::{not_equal, equal}

///|
#deprecated
pub extend StateExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend StateExpr with Show::{to_string, output}

///|
#deprecated
pub extend StateFlavor with Eq::{not_equal, equal}

///|
#deprecated
pub extend TensorProductExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend TensorProductExpr with Show::{to_string, output}

///|
#deprecated
pub extend WGateExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend WavefunctionExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend Wigner3j with Eq::{not_equal, equal}

///|
#deprecated
pub extend Wigner6j with Eq::{not_equal, equal}

///|
#deprecated
pub extend Wigner9j with Eq::{not_equal, equal}

///|
#deprecated
pub extend WignerDExpr with Eq::{not_equal, equal}

///|
#deprecated
pub extend WignerDExpr with Show::{to_string, output}
