///|
#deprecated
pub extend DifferentialOperator with Add::{add}

///|
#deprecated
pub extend DifferentialOperator with Eq::{not_equal, equal}

///|
#deprecated
pub extend DifferentialOperator with Mul::{mul}

///|
#deprecated
pub extend DifferentialOperator with Show::{to_string, output}

///|
#deprecated
pub extend DifferentialOperatorAlgebra with Eq::{not_equal, equal}

///|
#deprecated
pub extend DifferentialOperatorAlgebra with Show::{to_string, output}

///|
#deprecated
pub extend HolonomicError with Show::{to_string, output}

///|
#deprecated
pub extend HolonomicFunction with Add::{add}

///|
#deprecated
pub extend HolonomicFunction with Eq::{not_equal, equal}

///|
#deprecated
pub extend HolonomicFunction with Mul::{mul}

///|
#deprecated
pub extend HolonomicFunction with Show::{to_string, output}

///|
#deprecated
pub extend HolonomicSequence with Eq::{not_equal, equal}

///|
#deprecated
pub extend HolonomicSequence with Show::{to_string, output}

///|
#deprecated
pub extend RecurrenceOperator with Add::{add}

///|
#deprecated
pub extend RecurrenceOperator with Eq::{not_equal, equal}

///|
#deprecated
pub extend RecurrenceOperator with Mul::{mul}

///|
#deprecated
pub extend RecurrenceOperator with Show::{to_string, output}

///|
#deprecated
pub extend RecurrenceOperatorAlgebra with Eq::{not_equal, equal}

///|
#deprecated
pub extend RecurrenceOperatorAlgebra with Show::{to_string, output}
