///|
/// Elementary hyperbolic functions.

///|
pub fn sinh(expr : Expr) -> Expr {
  @symcore.function("sinh", [expr])
}

///|
pub fn cosh(expr : Expr) -> Expr {
  @symcore.function("cosh", [expr])
}

///|
pub fn tanh(expr : Expr) -> Expr {
  @symcore.function("tanh", [expr])
}

///|
pub fn coth(expr : Expr) -> Expr {
  @symcore.function("coth", [expr])
}

///|
pub fn sech(expr : Expr) -> Expr {
  @symcore.function("sech", [expr])
}

///|
pub fn csch(expr : Expr) -> Expr {
  @symcore.function("csch", [expr])
}

///|
pub fn asinh(expr : Expr) -> Expr {
  @symcore.function("asinh", [expr])
}

///|
pub fn acosh(expr : Expr) -> Expr {
  @symcore.function("acosh", [expr])
}

///|
pub fn atanh(expr : Expr) -> Expr {
  @symcore.function("atanh", [expr])
}

///|
pub fn acoth(expr : Expr) -> Expr {
  @symcore.function("acoth", [expr])
}

///|
pub fn asech(expr : Expr) -> Expr {
  @symcore.function("asech", [expr])
}

///|
pub fn acsch(expr : Expr) -> Expr {
  @symcore.function("acsch", [expr])
}
