///|
#deprecated
pub extend ComplexFloat with Add::{add}

///|
#deprecated
pub extend ComplexFloat with Eq::{not_equal, equal}

///|
#deprecated
pub extend ComplexFloat with Mul::{mul}

///|
#deprecated
pub extend ComplexFloat with Neg::{neg}

///|
#deprecated
pub extend ComplexFloat with Show::{to_string, output}

///|
#deprecated
pub extend Expr with @moonbitlang/core/debug.Debug::{to_repr}

///|
#deprecated
pub extend Expr with Add::{add}

///|
#deprecated
pub extend Expr with BitXOr::{lxor}

///|
#deprecated
pub extend Expr with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
#deprecated
pub extend Expr with Eq::{not_equal, equal}

///|
#deprecated
pub extend Expr with Hash::{hash, hash_combine}

///|
#deprecated
pub extend Expr with Mul::{mul}

///|
#deprecated
pub extend Expr with Sub::{sub}

///|
#deprecated
pub extend Float with Add::{add}

///|
#deprecated
pub extend Float with Eq::{not_equal, equal}

///|
#deprecated
pub extend Float with Mul::{mul}

///|
#deprecated
pub extend Float with Neg::{neg}

///|
#deprecated
pub extend Float with Show::{to_string, output}
