#!/usr/bin/env python3

from __future__ import annotations

import argparse
import dataclasses
import os
import pathlib
import re
import sys
import textwrap
from typing import Iterable


REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC_ROOT = REPO_ROOT / "src"
STRICT_PACKAGES_FILE = REPO_ROOT / "docs" / "docstring-strict-packages.txt"
GENERATED_MARKER = (
    "<!-- GENERATED by tools/package_docs.py. "
    "Edit this tool metadata or replace the file and remove this marker. -->"
)

FORBIDDEN_PLACEHOLDER_PATTERNS = [
    "refer to sympy",
    "same as sympy",
    "参考sympy",
    "参考 sympy",
    "see sympy",
]

FORBIDDEN_USER_DOC_TERMS = [
    "sympy",
]

EXACT_SUMMARIES: dict[str, str] = {
    "symalgebras": (
        "Quaternion arithmetic and small algebraic helper objects that are useful "
        "in geometric, kinematic, and symbolic rotation code."
    ),
    "symassume": (
        "Assumptions, predicates, and query evaluation for symbolic facts such as "
        "realness, positivity, parity, and logical combinations of those facts."
    ),
    "symcalculus": (
        "Symbolic calculus utilities including singularities, accumulation bounds, "
        "finite-difference helpers, and Euler-Lagrange style operators."
    ),
    "symcategories": (
        "Category-theoretic objects, morphisms, diagrams, and rendering helpers "
        "for reasoning about categorical structure symbolically."
    ),
    "symcombinatorics": (
        "Permutation groups, free groups, Gray codes, partitions, tableaux, and "
        "other combinatorial structures and algorithms."
    ),
    "symconcrete": (
        "Summation, product, and recurrence helpers for concrete mathematics over "
        "symbolic expressions and symbolic bounds."
    ),
    "symcore": (
        "The foundational expression package for Symbit. It defines the symbolic "
        "expression tree, exact numeric leaves, callable heads, and structural "
        "traversal primitives used everywhere else in the module."
    ),
    "symdiscrete": (
        "Discrete transforms and convolution algorithms, including FFT, FWHT, NTT, "
        "and subset-transform style helpers."
    ),
    "symfunctions": (
        "The umbrella package for symbolic function constructors. It provides the "
        "public entry points used to build named symbolic function applications."
    ),
    "symgeometry": (
        "Symbolic planar and spatial geometry: points, lines, circles, conics, "
        "polygons, curves, and geometric predicates."
    ),
    "symholonomic": (
        "Holonomic-function and recurrence-operator support for translating between "
        "symbolic expressions and holonomic representations."
    ),
    "symintegrals": (
        "Symbolic integration and transform helpers, including direct integration, "
        "special-case integrators, and Fourier/Laplace-family transforms."
    ),
    "symliealgebras": (
        "Lie algebra data such as Cartan types, Cartan matrices, Dynkin diagrams, "
        "and related matrix helpers."
    ),
    "symlogic": (
        "Boolean algebra expressions, satisfiability helpers, normal forms, and "
        "logical rewriting utilities."
    ),
    "symmatrices": (
        "Dense, sparse, and symbolic matrix objects together with linear algebra, "
        "matrix-expression construction, and decomposition utilities."
    ),
    "symntheory": (
        "Number-theory algorithms such as primes, modular arithmetic, continued "
        "fractions, multiplicative functions, and related arithmetic helpers."
    ),
    "symnum": (
        "Low-level numeric support used across Symbit, including exact rationals, "
        "MP-based numeric helpers, and precision-management utilities."
    ),
    "symparse": (
        "Parsing infrastructure for turning textual mathematics into Symbit "
        "expressions: lexer, AST, lowering, and parse options."
    ),
    "symphysics": (
        "The umbrella physics package. It collects public constants, units, optics, "
        "quantum helpers, mechanics utilities, and related symbolic physics APIs."
    ),
    "sympolys": (
        "Polynomial domains, polynomial arithmetic, factorization, root finding, "
        "Groebner-style helpers, and compatibility layers around symbolic polys."
    ),
    "symprint": (
        "String and LaTeX printers for symbolic expressions. Use this package when "
        "you need stable textual output or configurable LaTeX rendering."
    ),
    "symseries": (
        "Series, limits, asymptotics, formal power series, and order-tracking "
        "utilities."
    ),
    "symsets": (
        "Symbolic sets, intervals, finite sets, images, products, and set-theoretic "
        "operations used by the solving and assumptions layers."
    ),
    "symsimplify": (
        "General-purpose and targeted simplification passes, rational rewrites, "
        "radical and trigonometric simplifiers, traversal tools, and CSE."
    ),
    "symsolvers": (
        "Equation solving, `solveset`, linear and nonlinear systems, ODE/PDE entry "
        "points, linear programming, and inequality reduction."
    ),
    "symstats": (
        "Random variables, distributions, stochastic processes, symbolic probability "
        "queries, and statistical helper objects."
    ),
    "symstrategies": (
        "Reusable strategy combinators for deterministic expression rewriting, tree "
        "rewrites, branch exploration, and traversal orchestration."
    ),
    "symtensor": (
        "Tensor-oriented public entry points and helpers for array, indexed, and "
        "tensor-expression workflows."
    ),
    "symunify": (
        "Term unification, Symbit-expression deconstruction/reconstruction, and "
        "rewrite-rule helpers."
    ),
    "symutilities": (
        "Assorted utility helpers for code generation, lambdify-style workflows, "
        "combinatorial utilities, memoization, and output capture."
    ),
    "symvector": (
        "Vector calculus, coordinate systems, orienters, dyadics, and three-"
        "dimensional symbolic vector operations."
    ),
    "symfunctions/combinatorial": (
        "Combinatorial symbolic functions such as factorial-family, gamma-adjacent, "
        "and sequence-oriented function constructors."
    ),
    "symfunctions/elementary": (
        "Elementary symbolic functions including trigonometric, exponential, "
        "logarithmic, and piecewise-style constructors."
    ),
    "symfunctions/special": (
        "Special-function constructors such as Bessel, hypergeometric, orthogonal-"
        "polynomial, and related higher transcendental functions."
    ),
    "symphysics/continuum_mechanics": (
        "Continuum-mechanics models and helpers layered on top of the broader "
        "physics package."
    ),
    "symphysics/control": (
        "Control-theory transfer functions, state-space objects, and analysis "
        "helpers in the symbolic physics stack."
    ),
    "symphysics/mechanics": (
        "Mechanics-oriented coordinate, body, particle, and kinematics utilities."
    ),
    "symphysics/quantum": (
        "Quantum states, operators, commutators, Hilbert-space helpers, and related "
        "symbolic quantum mechanics building blocks."
    ),
    "symphysics/secondquant": (
        "Second-quantization objects and operator algebra layered on top of the "
        "quantum portion of the physics stack."
    ),
    "symphysics/vector": (
        "Physics-oriented vector helpers that complement the more general "
        "`symvector` package."
    ),
    "symstrategies/branch": (
        "Branching strategy combinators for rewrite pipelines that return multiple "
        "candidates rather than a single deterministic result."
    ),
    "symstrategies/branch/core": (
        "Core branching strategy primitives shared by the higher-level branch "
        "strategy packages."
    ),
    "symstrategies/branch/tools": (
        "Tooling helpers for assembling and inspecting branch-oriented strategy "
        "pipelines."
    ),
    "symstrategies/branch/traverse": (
        "Traversal helpers for branch-producing rewrite strategies over trees and "
        "expression structures."
    ),
    "symstrategies/core": (
        "The core deterministic strategy combinators used by the rest of the "
        "strategies subsystem."
    ),
    "symstrategies/rl": (
        "Rule-language helpers and substitution/rebuild primitives for declarative "
        "rewriting workflows."
    ),
    "symstrategies/tools": (
        "Utility helpers for building, debugging, and adapting strategy pipelines."
    ),
    "symstrategies/traverse": (
        "Traversal combinators and tree-walk helpers for deterministic rewrite "
        "strategies."
    ),
    "symstrategies/tree": (
        "Tree-oriented strategies and helper abstractions used to express recursive "
        "rewrite logic."
    ),
    "symstrategies/util": (
        "Shared strategy utility types, function bundles, and lower-level helpers."
    ),
    "symtensor/array": (
        "Array-expression helpers and n-dimensional tensor-array operations."
    ),
    "symtensor/indexed": (
        "Indexed bases, indexed expressions, and index-aware tensor notation."
    ),
    "symtensor/tensor": (
        "Higher-level tensor-expression objects and tensor canonicalization helpers."
    ),
}

RELATED_PACKAGES: dict[str, list[str]] = {
    "symassume": ["CAIMEOX/symbit/symlogic", "CAIMEOX/symbit/symsets"],
    "symcalculus": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symseries"],
    "symcategories": ["CAIMEOX/symbit/symcore"],
    "symcombinatorics": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symutilities"],
    "symconcrete": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symseries"],
    "symcore": ["CAIMEOX/symbit", "CAIMEOX/symbit/symsimplify"],
    "symdiscrete": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symnum"],
    "symfunctions": ["CAIMEOX/symbit/symcore"],
    "symgeometry": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symsets"],
    "symholonomic": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symseries"],
    "symintegrals": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symfunctions"],
    "symlogic": ["CAIMEOX/symbit/symassume", "CAIMEOX/symbit/symsets"],
    "symmatrices": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/sympolys"],
    "symparse": ["CAIMEOX/symbit", "CAIMEOX/symbit/symcore"],
    "symphysics": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symvector"],
    "sympolys": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symmatrices"],
    "symprint": ["CAIMEOX/symbit", "CAIMEOX/symbit/symcore"],
    "symseries": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symintegrals"],
    "symsets": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symlogic"],
    "symsimplify": ["CAIMEOX/symbit", "CAIMEOX/symbit/symcore"],
    "symsolvers": [
        "CAIMEOX/symbit/symcore",
        "CAIMEOX/symbit/sympolys",
        "CAIMEOX/symbit/symsets",
    ],
    "symstats": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symsets"],
    "symstrategies": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symsimplify"],
    "symtensor": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symmatrices"],
    "symunify": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symstrategies/rl"],
    "symutilities": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symprint"],
    "symvector": ["CAIMEOX/symbit/symcore", "CAIMEOX/symbit/symphysics"],
}

CURATED_EXAMPLES: dict[str, str] = {
    "symcore": """\
```mbt check
///|
test "symcore builds structured expressions" {
  let x = Expr::Symbol("x")
  let expr = add([x, int(1)])
  inspect(@symprint.to_string(expr), content="x + 1")
}
```""",
    "symsets": """\
```mbt check
///|
test "symsets builds intervals and finite sets" {
  let interval_set = interval(@symcore.int(0), @symcore.int(1))
  let finite = finite_set([@symcore.int(0), @symcore.int(1)])
  inspect(compare_set(interval_set, interval_set), content="0")
  inspect(compare_set(finite, finite), content="0")
}
```""",
    "symsimplify": """\
```mbt check
///|
test "symsimplify runs targeted simplifiers" {
  let x = @symcore.Expr::Symbol("x")
  let expr = @symcore.mul([x, @symcore.pow(x, @symcore.int(-1))])
  inspect(@symprint.to_string(simplify(expr)), content="1")
}
```""",
    "symprint": """\
```mbt check
///|
test "symprint renders plain text and latex" {
  let x = @symcore.Expr::Symbol("x")
  let expr = @symcore.add([x, @symcore.int(1)])
  inspect(to_string(expr), content="x + 1")
  inspect(latex(expr), content="x + 1")
}
```""",
    "symsolvers": """\
```mbt check
///|
test "symsolvers solves a linear equation" {
  let x = @symcore.Expr::Symbol("x")
  let solution = solveset(
    @symcore.add([x, @symcore.int(-1)]),
    symbol=Some(x),
    domain=@symsets.reals(),
  )
  inspect(solution, content="{1}")
}
```""",
    "sympolys": """\
```mbt check
///|
test "sympolys parses domain specifications" {
  let domain = domain_from_string("ZZ")
  inspect(domain_is_zz_pred(domain), content="true")
}
```""",
    "symunify": """\
```mbt check
///|
test "symunify can deconstruct and rebuild expressions" {
  let x = @symcore.Expr::Symbol("x")
  let term = deconstruct(@symcore.add([x, @symcore.int(1)]))
  inspect(@symprint.to_string(construct(term)), content="x + 1")
}
```""",
    "symvector": """\
```mbt check
///|
test "symvector exposes coordinate systems" {
  let _ = coord_sys3d("N")
  inspect(true, content="true")
}
```""",
    "symparse": """\
```mbt check
///|
test "symparse lowers text into expressions" {
  let expr = parse_expr("x + 1")
  inspect(@symprint.to_string(expr), content="x + 1")
}
```""",
}


@dataclasses.dataclass(frozen=True)
class Export:
    kind: str
    name: str


@dataclasses.dataclass(frozen=True)
class PackageInfo:
    rel_path: str
    dir_path: pathlib.Path
    import_path: str
    exports: list[Export]


@dataclasses.dataclass(frozen=True)
class SourceExport:
    kind: str
    name: str
    path: pathlib.Path
    line_no: int
    doc_text: str
    doc_has_text: bool
    doc_present: bool


MBTI_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("fn", re.compile(r"^pub fn(?:\[[^\]]+\])?\s+([A-Za-z_][\w]*(?:::[A-Za-z_][\w]*)?)")),
    ("let", re.compile(r"^pub let\s+([A-Za-z_][\w]*)")),
    ("suberror", re.compile(r"^pub(?:\([^)]+\))?\s+suberror\s+([A-Za-z_][\w]*)")),
    ("enum", re.compile(r"^pub enum\s+([A-Za-z_][\w]*)")),
    ("struct", re.compile(r"^pub struct\s+([A-Za-z_][\w]*)")),
    ("type", re.compile(r"^pub type\s+([A-Za-z_][\w]*)")),
    ("trait", re.compile(r"^pub trait\s+([A-Za-z_][\w]*)")),
    ("using", re.compile(r"^pub using .*{type ([A-Za-z_][\w]*)}")),
]

SOURCE_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("fn", re.compile(r"^pub fn(?:\[[^\]]+\])?\s+([A-Za-z_][\w]*(?:::[A-Za-z_][\w]*)?)")),
    ("let", re.compile(r"^pub let\s+([A-Za-z_][\w]*)")),
    ("suberror", re.compile(r"^pub(?:\([^)]+\))?\s+suberror\s+([A-Za-z_][\w]*)")),
    ("enum", re.compile(r"^pub enum\s+([A-Za-z_][\w]*)")),
    ("struct", re.compile(r"^pub struct\s+([A-Za-z_][\w]*)")),
    ("type", re.compile(r"^pub type\s+([A-Za-z_][\w]*)")),
    ("trait", re.compile(r"^pub trait\s+([A-Za-z_][\w]*)")),
]


def main() -> int:
    parser = argparse.ArgumentParser(description="Synchronize and validate Symbit package docs.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    sync_parser = subparsers.add_parser("sync-readmes", help="Generate or refresh package README.mbt.md files.")
    sync_parser.add_argument("--check", action="store_true", help="Fail instead of writing files.")

    subparsers.add_parser("report", help="Print doc coverage and README inventory.")
    subparsers.add_parser("check", help="Validate README presence, placeholder-free docs, and strict docstring coverage.")

    args = parser.parse_args()
    if args.command == "sync-readmes":
        return sync_readmes(check_only=args.check)
    if args.command == "report":
        return report_docs()
    if args.command == "check":
        return check_docs()
    parser.error("unknown command")
    return 2


def discover_packages() -> list[PackageInfo]:
    packages: list[PackageInfo] = []
    for moon_pkg in sorted(SRC_ROOT.rglob("moon.pkg")):
        if "sympy" in moon_pkg.parts:
            continue
        dir_path = moon_pkg.parent
        mbti_path = dir_path / "pkg.generated.mbti"
        if not mbti_path.exists():
            continue
        rel = os.path.relpath(dir_path, SRC_ROOT)
        rel_path = "." if rel == "." else rel.replace(os.sep, "/")
        import_path = parse_import_path(mbti_path)
        exports = parse_mbti_exports(mbti_path)
        packages.append(PackageInfo(rel_path, dir_path, import_path, exports))
    return packages


def parse_import_path(mbti_path: pathlib.Path) -> str:
    for line in mbti_path.read_text().splitlines():
        match = re.match(r'^package "([^"]+)"$', line.strip())
        if match:
            return match.group(1)
    raise RuntimeError(f"cannot read package import path from {mbti_path}")


def parse_mbti_exports(mbti_path: pathlib.Path) -> list[Export]:
    exports: list[Export] = []
    for line in mbti_path.read_text().splitlines():
        stripped = line.strip()
        for kind, pattern in MBTI_PATTERNS:
            match = pattern.match(stripped)
            if match:
                exports.append(Export(kind, match.group(1)))
                break
    return exports


def non_test_source_files(package: PackageInfo) -> list[pathlib.Path]:
    files: list[pathlib.Path] = []
    for path in sorted(package.dir_path.glob("*.mbt")):
        if path.name.endswith(("_test.mbt", "_wbtest.mbt", "_port_test.mbt")):
            continue
        files.append(path)
    return files


def parse_source_exports(package: PackageInfo) -> list[SourceExport]:
    exports: list[SourceExport] = []
    for path in non_test_source_files(package):
        lines = path.read_text().splitlines()
        doc_lines: list[str] = []
        for index, raw_line in enumerate(lines, start=1):
            stripped = raw_line.strip()
            if stripped.startswith("///"):
                doc_lines.append(stripped)
                continue
            export = parse_source_export(stripped)
            if export is not None:
                exports.append(
                    SourceExport(
                        kind=export.kind,
                        name=export.name,
                        path=path,
                        line_no=index,
                        doc_text=doc_block_text(doc_lines),
                        doc_has_text=doc_block_has_text(doc_lines),
                        doc_present=bool(doc_lines),
                    )
                )
            if stripped != "":
                doc_lines = []
    return exports


def parse_source_export(line: str) -> Export | None:
    for kind, pattern in SOURCE_PATTERNS:
        match = pattern.match(line)
        if match:
            return Export(kind, match.group(1))
    return None


def doc_block_has_text(lines: list[str]) -> bool:
    for line in lines:
        content = line[3:].strip()
        if content and content != "|":
            return True
    return False


def doc_block_text(lines: list[str]) -> str:
    rendered: list[str] = []
    for line in lines:
        content = line[3:]
        if content.startswith("|"):
            content = content[1:]
        rendered.append(content.lstrip())
    return "\n".join(rendered).strip()


def strict_packages() -> set[str]:
    if not STRICT_PACKAGES_FILE.exists():
        return set()
    selected: set[str] = set()
    for raw_line in STRICT_PACKAGES_FILE.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        selected.add(line)
    return selected


def summary_for(rel_path: str) -> str:
    if rel_path == ".":
        return (
            "The root `CAIMEOX/symbit` package is the compact public facade over the "
            "broader Symbit runtime. It focuses on expression construction, printing, "
            "common simplification entry points, and matrix helpers."
        )
    return EXACT_SUMMARIES.get(
        rel_path,
        "This package is a public Symbit runtime package. Import it directly when you "
        "need the subsystem-specific types and algorithms exposed here instead of the "
        "smaller root facade.",
    )


def related_packages_for(rel_path: str) -> list[str]:
    if rel_path in RELATED_PACKAGES:
        return RELATED_PACKAGES[rel_path]
    if rel_path.startswith("symfunctions/"):
        return ["CAIMEOX/symbit/symfunctions", "CAIMEOX/symbit/symcore"]
    if rel_path.startswith("symphysics/"):
        return ["CAIMEOX/symbit/symphysics", "CAIMEOX/symbit/symcore"]
    if rel_path.startswith("symstrategies/"):
        return ["CAIMEOX/symbit/symstrategies", "CAIMEOX/symbit/symsimplify"]
    if rel_path.startswith("symtensor/"):
        return ["CAIMEOX/symbit/symtensor", "CAIMEOX/symbit/symcore"]
    return ["CAIMEOX/symbit", "CAIMEOX/symbit/symcore"]


def key_exports(exports: Iterable[Export], limit: int = 8) -> list[str]:
    names: list[str] = []
    for export in exports:
        if export.kind == "using":
            continue
        if export.name.startswith("_"):
            continue
        if "::" in export.name:
            continue
        if export.name in names:
            continue
        names.append(export.name)
        if len(names) == limit:
            break
    return names


def smoke_export(exports: Iterable[Export]) -> Export | None:
    for export in exports:
        if export.kind == "using":
            continue
        if export.name.startswith("_"):
            continue
        if "::" in export.name:
            continue
        if export.kind in {"let", "fn", "type", "enum", "struct", "suberror"}:
            return export
    return None


def smoke_example(package: PackageInfo) -> str:
    export = smoke_export(package.exports)
    body = "inspect(true, content=\"true\")"
    if export is not None:
        if export.kind in {"let", "fn"}:
            body = f"let _ = {export.name}\ninspect(true, content=\"true\")"
        else:
            body = f"let _ : {export.name}? = None\ninspect(true, content=\"true\")"
    title = package.rel_path.replace("/", "_").replace(".", "root")
    indented_body = "\n".join(f"  {line}" for line in body.splitlines())
    return "\n".join(
        [
            "```mbt check",
            "///|",
            f'test "{title} public API is available" {{',
            indented_body,
            "}",
            "```",
        ]
    )


def spec_path_for(package: PackageInfo) -> str | None:
    if package.rel_path == ".":
        return None
    stem = package.rel_path.split("/")[0].replace("sym", "")
    candidate = REPO_ROOT / "docs" / "specs" / f"{stem}.md"
    if not candidate.exists():
        return None
    return os.path.relpath(candidate, package.dir_path).replace(os.sep, "/")


def generated_readme(package: PackageInfo) -> str:
    title = "CAIMEOX/symbit" if package.rel_path == "." else package.rel_path
    summary = summary_for(package.rel_path)
    keys = key_exports(package.exports)
    related = related_packages_for(package.rel_path)
    spec_path = spec_path_for(package)
    example = CURATED_EXAMPLES.get(package.rel_path, smoke_example(package))

    key_lines = [f"- `{name}`" for name in keys]
    if not key_lines:
        key_lines = ["- This package currently exports only advanced or method-heavy APIs."]
    related_lines = [f"- `{name}`" for name in related]

    lines = [
        GENERATED_MARKER,
        "",
        f"# {title}",
        "",
        f"`{package.import_path}` is the public import path for this package.",
        "",
        summary,
        "",
        "## When To Use This Package",
        "",
        f"- Import `{package.import_path}` directly when your code depends on this package's subsystem-specific types or algorithms.",
        "- Prefer this package over the root facade when you want the focused API surface listed below rather than a convenience wrapper.",
        "- Treat the example in this README as a regression test: if the public calling style changes, `moon test` should catch the drift.",
        "",
        "## Key Public Entry Points",
        "",
        *key_lines,
        "",
        "## Example",
        "",
        example.rstrip(),
        "",
        "## Related Packages",
        "",
        *related_lines,
    ]
    if spec_path is not None:
        lines.extend(
            [
                "",
                "## Further Reading",
                "",
                f"- [`{spec_path}`]({spec_path})",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def sync_readmes(check_only: bool) -> int:
    failures: list[str] = []
    writes: list[pathlib.Path] = []
    for package in discover_packages():
        readme = package.dir_path / "README.mbt.md"
        if package.rel_path == ".":
            continue
        content = generated_readme(package)
        if readme.exists() and GENERATED_MARKER not in readme.read_text():
            continue
        if not readme.exists() or readme.read_text() != content:
            if check_only:
                failures.append(str(readme))
            else:
                readme.write_text(content)
                writes.append(readme)
    if check_only and failures:
        for path in failures:
            print(f"README out of date: {path}", file=sys.stderr)
        return 1
    if not check_only:
        for path in writes:
            print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


def report_docs() -> int:
    packages = discover_packages()
    strict = strict_packages()
    print("package\treadme\texports\tsource_public\tdoc_coverage\tstrict")
    for package in packages:
        readme = package.dir_path / "README.mbt.md"
        source_exports = parse_source_exports(package)
        documented = sum(1 for item in source_exports if item.doc_has_text)
        total = len(source_exports)
        coverage = "n/a" if total == 0 else f"{documented}/{total}"
        strict_flag = "yes" if package.rel_path in strict else "no"
        print(
            f"{package.rel_path}\t"
            f"{'yes' if readme.exists() else 'no'}\t"
            f"{len(package.exports)}\t"
            f"{total}\t"
            f"{coverage}\t"
            f"{strict_flag}"
        )
    return 0


def check_docs() -> int:
    failures: list[str] = []
    packages = discover_packages()
    strict = strict_packages()

    for package in packages:
        readme = package.dir_path / "README.mbt.md"
        if not readme.exists():
            failures.append(f"missing README.mbt.md for package {package.rel_path}")
            continue
        readme_text = readme.read_text()
        if "# " not in readme_text:
            failures.append(f"README missing top-level heading: {readme.relative_to(REPO_ROOT)}")
        if "```mbt check" not in readme_text and "```mbt nocheck" not in readme_text:
            failures.append(f"README missing example block: {readme.relative_to(REPO_ROOT)}")
        failures.extend(placeholder_doc_hits(readme, readme_text))
        failures.extend(user_doc_term_hits(readme, readme_text))

        if package.rel_path not in strict:
            continue
        source_exports = parse_source_exports(package)
        by_name = {(item.kind, item.name): item for item in source_exports}
        expected = [
            export
            for export in package.exports
            if export.kind != "using" and not export.name.startswith("_")
        ]
        missing = []
        for export in expected:
            matched = by_name.get((export.kind, export.name))
            if matched is None:
                missing.append(f"{export.kind} {export.name} (not found in source scan)")
                continue
            if not matched.doc_has_text:
                location = matched.path.relative_to(REPO_ROOT)
                missing.append(f"{export.kind} {export.name} ({location}:{matched.line_no})")
            failures.extend(user_doc_term_hits(matched.path, matched.doc_text, line_no=matched.line_no))
        if missing:
            failures.append(
                "missing nontrivial docstrings in strict package "
                f"{package.rel_path}: " + ", ".join(missing[:12]) +
                (" ..." if len(missing) > 12 else "")
            )

    for path in iter_runtime_doc_files():
        if path.name == "README.mbt.md" and path.parent == SRC_ROOT:
            continue
        failures.extend(placeholder_doc_hits(path, path.read_text()))

    for path in [
        REPO_ROOT / "README.mbt.md",
        REPO_ROOT / "src" / "README.mbt.md",
        REPO_ROOT / "docs" / "documentation-style.md",
    ]:
        if path.exists():
            failures.extend(user_doc_term_hits(path, path.read_text()))

    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1
    print("documentation checks passed")
    return 0


def placeholder_doc_hits(path: pathlib.Path, text: str) -> list[str]:
    lowered = text.lower()
    hits: list[str] = []
    for pattern in FORBIDDEN_PLACEHOLDER_PATTERNS:
        if pattern in lowered:
            hits.append(
                f"forbidden placeholder phrase {pattern!r} in {path.relative_to(REPO_ROOT)}"
            )
    return hits


def user_doc_term_hits(path: pathlib.Path, text: str, line_no: int | None = None) -> list[str]:
    lowered = text.lower()
    hits: list[str] = []
    for term in FORBIDDEN_USER_DOC_TERMS:
        if term in lowered:
            location = path.relative_to(REPO_ROOT)
            if line_no is not None:
                location = f"{location}:{line_no}"
            hits.append(
                f"forbidden upstream reference {term!r} in {location}"
            )
    return hits


def iter_runtime_doc_files() -> Iterable[pathlib.Path]:
    seen: set[pathlib.Path] = set()
    for ext in ("*.mbt", "*.md", "*.mbt.md"):
        for path in REPO_ROOT.rglob(ext):
            if path in seen:
                continue
            seen.add(path)
            if (
                "target" in path.parts
                or ".mooncakes" in path.parts
                or "sympy" in path.parts
                or "_build" in path.parts
            ):
                continue
            yield path


if __name__ == "__main__":
    raise SystemExit(main())
